#!/usr/bin/env python3

import sys
import os
from checkers import *
from metadata import *

def parse_args(args):

	if len(args) < 1:
		print("Error: Usage: ./scorpion FILE1 [FILE2 ...]")
		sys.exit(1)

	arg_values = {
		'files' : []
	}

	arg_values['files'] = args

	if len(arg_values['files']) == 0:
		print("Error: Please provide 1 or more files")
		sys.exit(1)
	
	if (not files_are_unique(arg_values['files'])):
		print("Error: Files cannot be duplicated")
		sys.exit(1)
	
	if not files_are_valid(arg_values['files']):
		sys.exit(1)

	return arg_values


def main(args):

	arg_values = parse_args(args)

	files = arg_values['files']

	for file in files:
		attributes = get_image_metadata(file)
		print(f'--- File {file} ---')
		print_metadata(attributes)
		print()


if __name__ == '__main__':
    main(sys.argv[1:])