#!/usr/bin/env python3

from checkers import *
from scrape import *
import sys
import pdb

#pdb.set_trace()


def main(args):

	args = parse_args(args)
    

	print('URL: ', args['url'])
	print('Depth Level: ', args['level'])
	print('Save Path: ', args['save_path'])

	scrape(args['url'], args['level'], args['save_path'])

if __name__ == '__main__':
    main(sys.argv[1:])