#!/usr/bin/env python3

from checkers import *
from scrape import *
import sys



def main(args):

	args = parse_args(args)
	for key, value in args.items():
		print(f"{key}: {value}")

	scrape(args['url'], args['level'], args['save_path'])

if __name__ == '__main__':
    main(sys.argv[1:])